debug = true

logLevel = "DEBUG"

defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
    entryPoint = "https"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "karrita.com"
watch = true
exposedByDefault = false
swarmMode = true
network = "net0"


[acme]
email = "sayf.piratos@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
